[package]
name = "email-worker"
version = "0.1.0"
authors = ["Luiz Carlos Mourão Paes de Carvalho <luizcarlosmpc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "1.2.1"
fern = "0.6.0"

lettre = "0.9.3"
lettre_email = "0.9.4"